# Generated by Django 2.1.4 on 2019-03-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190313_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(default='2019-03-13 19:39:36.583998'),
        ),
    ]
