# Generated by Django 2.1.7 on 2019-03-14 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20190313_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 19, 17, 13, 172152)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='todo_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
