# Generated by Django 2.1.7 on 2019-03-14 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20190314_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='todo_author',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 19, 27, 53, 480201)),
        ),
    ]
