# Generated by Django 2.1.7 on 2019-03-14 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20190314_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 19, 30, 17, 287509)),
        ),
    ]
