# Generated by Django 2.1.7 on 2019-03-14 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20190314_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='todo_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 21, 53, 35, 492884)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 21, 53, 35, 492884)),
        ),
    ]
